server:
  port: 8081

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanchezih/dla-microservices.git
          searchPaths: config-data
          username: sanchezih
          password: ${DLA_MS_PASSWD}
  security:
    user:
      name: root
      password: s3cr3t